name: Build and test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.100
      - name: Build and test
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test
